<?php

use App\Buttons;
use App\UserGroups;
use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DatabaseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        UserGroups::create([
                'name' => 'default',
                'description' => 'General Public',
            ]
        );

        $buttons = array(
            [
                'user_group' => 1,
                'evolution' => 1,
                'button_label' => 'Problem with me E1B1',
                'cause1' => 'Short Fused',
                'cause2' => 'Over Caring',
                'cause3' => 'Highly Concerned',
                'cause4' => 'Absent minded',
                'cause5' => 'Angry',
                'node' => 'E1B1',
                'branch1' => 'E2B1',
                'branch2' => 'E2B2',
            ],
            [
                'user_group' => 1,
                'evolution' => 1,
                'button_label' => 'Problem with world E1B2',
                'cause1' => 'Dominating',
                'cause2' => 'Selfish',
                'cause3' => 'Bare society',
                'cause4' => 'Bad Education',
                'cause5' => 'Money Minded',
                'node' => 'E1B2',
                'branch1' => 'E2B3',
                'branch2' => 'E2B4',
            ],
            [
                'user_group' => 1,
                'evolution' => 2,
                'button_label' => 'Problem with world E2B1',
                'cause1' => 'Dominating',
                'cause2' => 'Selfish',
                'cause3' => 'Bare society',
                'cause4' => 'Bad Education',
                'cause5' => 'Money Minded',
                'node' => 'E2B1',
                'branch1' => 'E3B1',
                'branch2' => 'E3B2',
            ],
            [
                'user_group' => 1,
                'evolution' => 2,
                'button_label' => 'Problem with world E2B2',
                'cause1' => 'Dominating',
                'cause2' => 'Selfish',
                'cause3' => 'Bare society',
                'cause4' => 'Bad Education',
                'cause5' => 'Money Minded',
                'node' => 'E2B2',
                'branch1' => 'E3B3',
                'branch2' => 'E3B4',
            ],
            [
                'user_group' => 1,
                'evolution' => 2,
                'button_label' => 'Problem with world E2B3',
                'cause1' => 'Dominating',
                'cause2' => 'Selfish',
                'cause3' => 'Bare society',
                'cause4' => 'Bad Education',
                'cause5' => 'Money Minded',
                'node' => 'E2B3',
                'branch1' => 'E3B5',
                'branch2' => 'E3B6',
            ],
            [
                'user_group' => 1,
                'evolution' => 2,
                'button_label' => 'Problem with world E2B4',
                'cause1' => 'Dominating',
                'cause2' => 'Selfish',
                'cause3' => 'Bare society',
                'cause4' => 'Bad Education',
                'cause5' => 'Money Minded',
                'node' => 'E2B4',
                'branch1' => 'E3B7',
                'branch2' => 'E3B8',
            ],
            [
                'user_group' => 1,
                'evolution' => 3,
                'button_label' => 'Problem with world E3B1',
                'cause1' => 'Dominating',
                'cause2' => 'Selfish',
                'cause3' => 'Bare society',
                'cause4' => 'Bad Education',
                'cause5' => 'Money Minded',
                'node' => 'E3B1',
                'branch1' => 'E4B1',
                'branch2' => 'E4B2',
            ],
            [
                'user_group' => 1,
                'evolution' => 3,
                'button_label' => 'Problem with world E3B2',
                'cause1' => 'Dominating',
                'cause2' => 'Selfish',
                'cause3' => 'Bare society',
                'cause4' => 'Bad Education',
                'cause5' => 'Money Minded',
                'node' => 'E3B2',
                'branch1' => 'E4B3',
                'branch2' => 'E4B4',
            ],
            [
                'user_group' => 1,
                'evolution' => 3,
                'button_label' => 'Problem with world E3B3',
                'cause1' => 'Dominating',
                'cause2' => 'Selfish',
                'cause3' => 'Bare society',
                'cause4' => 'Bad Education',
                'cause5' => 'Money Minded',
                'node' => 'E3B3',
                'branch1' => 'E4B5',
                'branch2' => 'E4B6',
            ],
            [
                'user_group' => 1,
                'evolution' => 3,
                'button_label' => 'Problem with world E3B4',
                'cause1' => 'Dominating',
                'cause2' => 'Selfish',
                'cause3' => 'Bare society',
                'cause4' => 'Bad Education',
                'cause5' => 'Money Minded',
                'node' => 'E3B4',
                'branch1' => 'E4B7',
                'branch2' => 'E4B8',
            ],
            [
                'user_group' => 1,
                'evolution' => 3,
                'button_label' => 'Problem with world E3B5',
                'cause1' => 'Dominating',
                'cause2' => 'Selfish',
                'cause3' => 'Bare society',
                'cause4' => 'Bad Education',
                'cause5' => 'Money Minded',
                'node' => 'E3B5',
                'branch1' => 'E4B9',
                'branch2' => 'E4B10',
            ],
            [
                'user_group' => 1,
                'evolution' => 3,
                'button_label' => 'Problem with world E3B6',
                'cause1' => 'Dominating',
                'cause2' => 'Selfish',
                'cause3' => 'Bare society',
                'cause4' => 'Bad Education',
                'cause5' => 'Money Minded',
                'node' => 'E3B6',
                'branch1' => 'E4B11',
                'branch2' => 'E4B12',
            ],
            [
                'user_group' => 1,
                'evolution' => 3,
                'button_label' => 'Problem with world E3B7',
                'cause1' => 'Dominating',
                'cause2' => 'Selfish',
                'cause3' => 'Bare society',
                'cause4' => 'Bad Education',
                'cause5' => 'Money Minded',
                'node' => 'E3B7',
                'branch1' => 'E4B13',
                'branch2' => 'E4B14',
            ],
            [
                'user_group' => 1,
                'evolution' => 3,
                'button_label' => 'Problem with world E3B8',
                'cause1' => 'Dominating',
                'cause2' => 'Selfish',
                'cause3' => 'Bare society',
                'cause4' => 'Bad Education',
                'cause5' => 'Money Minded',
                'node' => 'E3B8',
                'branch1' => 'E4B15',
                'branch2' => 'E4B16',
            ],
            [
                'user_group' => 1,
                'evolution' => 4,
                'button_label' => 'Problem with world E4B1',
                'cause1' => 'Dominating',
                'cause2' => 'Selfish',
                'cause3' => 'Bare society',
                'cause4' => 'Bad Education',
                'cause5' => 'Money Minded',
                'node' => 'E4B1',
                'branch1' => null,
                'branch2' => null,
            ],
            [
                'user_group' => 1,
                'evolution' => 4,
                'button_label' => 'Problem with world E4B2',
                'cause1' => 'Dominating',
                'cause2' => 'Selfish',
                'cause3' => 'Bare society',
                'cause4' => 'Bad Education',
                'cause5' => 'Money Minded',
                'node' => 'E4B2',
                'branch1' => null,
                'branch2' => null,
            ],
            [
                'user_group' => 1,
                'evolution' => 4,
                'button_label' => 'Problem with world E4B3',
                'cause1' => 'Dominating',
                'cause2' => 'Selfish',
                'cause3' => 'Bare society',
                'cause4' => 'Bad Education',
                'cause5' => 'Money Minded',
                'node' => 'E4B3',
                'branch1' => null,
                'branch2' => null,
            ],
            [
                'user_group' => 1,
                'evolution' => 4,
                'button_label' => 'Problem with world E4B4',
                'cause1' => 'Dominating',
                'cause2' => 'Selfish',
                'cause3' => 'Bare society',
                'cause4' => 'Bad Education',
                'cause5' => 'Money Minded',
                'node' => 'E4B4',
                'branch1' => null,
                'branch2' => null,
            ],
            [
                'user_group' => 1,
                'evolution' => 4,
                'button_label' => 'Problem with world E4B5',
                'cause1' => 'Dominating',
                'cause2' => 'Selfish',
                'cause3' => 'Bare society',
                'cause4' => 'Bad Education',
                'cause5' => 'Money Minded',
                'node' => 'E4B5',
                'branch1' => null,
                'branch2' => null,
            ],
            [
                'user_group' => 1,
                'evolution' => 4,
                'button_label' => 'Problem with world E4B6',
                'cause1' => 'Dominating',
                'cause2' => 'Selfish',
                'cause3' => 'Bare society',
                'cause4' => 'Bad Education',
                'cause5' => 'Money Minded',
                'node' => 'E4B6',
                'branch1' => null,
                'branch2' => null,
            ],
            [
                'user_group' => 1,
                'evolution' => 4,
                'button_label' => 'Problem with world E4B7',
                'cause1' => 'Dominating',
                'cause2' => 'Selfish',
                'cause3' => 'Bare society',
                'cause4' => 'Bad Education',
                'cause5' => 'Money Minded',
                'node' => 'E4B7',
                'branch1' => null,
                'branch2' => null,
            ],
            [
                'user_group' => 1,
                'evolution' => 4,
                'button_label' => 'Problem with world E4B8',
                'cause1' => 'Dominating',
                'cause2' => 'Selfish',
                'cause3' => 'Bare society',
                'cause4' => 'Bad Education',
                'cause5' => 'Money Minded',
                'node' => 'E4B8',
                'branch1' => null,
                'branch2' => null,
            ],
            [
                'user_group' => 1,
                'evolution' => 4,
                'button_label' => 'Problem with world E4B9',
                'cause1' => 'Dominating',
                'cause2' => 'Selfish',
                'cause3' => 'Bare society',
                'cause4' => 'Bad Education',
                'cause5' => 'Money Minded',
                'node' => 'E4B9',
                'branch1' => null,
                'branch2' => null,
            ],
            [
                'user_group' => 1,
                'evolution' => 4,
                'button_label' => 'Problem with world E4B10',
                'cause1' => 'Dominating',
                'cause2' => 'Selfish',
                'cause3' => 'Bare society',
                'cause4' => 'Bad Education',
                'cause5' => 'Money Minded',
                'node' => 'E4B10',
                'branch1' => null,
                'branch2' => null,
            ],
            [
                'user_group' => 1,
                'evolution' => 4,
                'button_label' => 'Problem with world E4B11',
                'cause1' => 'Dominating',
                'cause2' => 'Selfish',
                'cause3' => 'Bare society',
                'cause4' => 'Bad Education',
                'cause5' => 'Money Minded',
                'node' => 'E4B11',
                'branch1' => null,
                'branch2' => null,
            ],
            [
                'user_group' => 1,
                'evolution' => 4,
                'button_label' => 'Problem with world E4B12',
                'cause1' => 'Dominating',
                'cause2' => 'Selfish',
                'cause3' => 'Bare society',
                'cause4' => 'Bad Education',
                'cause5' => 'Money Minded',
                'node' => 'E4B12',
                'branch1' => null,
                'branch2' => null,
            ],
            [
                'user_group' => 1,
                'evolution' => 4,
                'button_label' => 'Problem with world E4B13',
                'cause1' => 'Dominating',
                'cause2' => 'Selfish',
                'cause3' => 'Bare society',
                'cause4' => 'Bad Education',
                'cause5' => 'Money Minded',
                'node' => 'E4B13',
                'branch1' => null,
                'branch2' => null,
            ],
            [
                'user_group' => 1,
                'evolution' => 4,
                'button_label' => 'Problem with world E4B14',
                'cause1' => 'Dominating',
                'cause2' => 'Selfish',
                'cause3' => 'Bare society',
                'cause4' => 'Bad Education',
                'cause5' => 'Money Minded',
                'node' => 'E4B14',
                'branch1' => null,
                'branch2' => null,
            ],
            [
                'user_group' => 1,
                'evolution' => 4,
                'button_label' => 'Problem with world E4B15',
                'cause1' => 'Dominating',
                'cause2' => 'Selfish',
                'cause3' => 'Bare society',
                'cause4' => 'Bad Education',
                'cause5' => 'Money Minded',
                'node' => 'E4B15',
                'branch1' => null,
                'branch2' => null,
            ],
            [
                'user_group' => 1,
                'evolution' => 4,
                'button_label' => 'Problem with world E4B16',
                'cause1' => 'Dominating',
                'cause2' => 'Selfish',
                'cause3' => 'Bare society',
                'cause4' => 'Bad Education',
                'cause5' => 'Money Minded',
                'node' => 'E4B16',
                'branch1' => null,
                'branch2' => null,
            ],
        );
        foreach($buttons as $button)
        {
            Buttons::create($button);
        }
    }
}
